package com.mmg.mysqlCluster.enums;

/**
 * @Auther: fan
 * @Date: 2021/12/8
 * @Description:
 */
public enum LockEnums {
    CAR_LOCK,
    SERVER_LOCK,
    USER_LOCK,
    USER_VEHICLE_LOCK,
    VEHICLE_PRICE_LOCK,
    PARKING_REMAINDER,
    ROLE_LOCK,
    RECORD_LOCK,
    USER_COUPON_LOCK,
    SHOP_ACCOUNT_LOCK,
    USER_BALANCE_LOCK,
    USER_BALANCE_FINISH_LOCK,
    USER_ORDER_LOCK,
    USER_PHONE_LOCK,
    USER_TOKEN_LOCK,
    CHANNEL_VEHICLE_LOCK,
    WS_ACCESS_TOKEN_LOCK,
//    WS_MESSAGE_LOCK,
    WS_TALK_LOCK,
    WS_TALKING,
    DEVICE_SCREEN_LOCK,
    ORDER_EXPORT_LOCK,
    FREE_CAR_LOCK,
    INVOICE_LOCK,
    PARKING_RECORD_PUSH_LOCK,
    VEHICLE_LEASE_ADD_LOCK,

    SCHEDULE_ROLLBACK_COUPON_LOCK,
    SCHEDULE_ISSUE_COUPON_LOCK,
    SCHEDULE_RENEW_COUPON_LOCK,
    SCHEDULE_IDLE_LOTS_LOCK,
    SCHEDULE_FREE_CAR_LOCK,

    USER_CHARGE_REFUND_LOCK,

    CAIYUN_WEATHER,

    ENTRANCE_OPEN,

    VALIDATE_CODE,

    REAL_PLAY,
    LOCK_REAL_PLAY,
    PRICE_UNIT,
    DUPLICATE_FEE_CHARGE,
    ;
}
